services:
    app:
        build: .
        container_name: book-app
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: bookdb
            DB_USERNAME: bookuser
            DB_PASSWORD: bookpass
            REDIS_HOST: redis
        depends_on:
            - db
            - redis
        networks:
            - book-network
        command: php artisan serve --host=0.0.0.0 --port=8080

    db:
        image: mariadb:10.8
        container_name: book-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bookdb
            MYSQL_USER: bookuser
            MYSQL_PASSWORD: bookpass
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - book-network

    redis:
        image: redis:6-alpine
        container_name: book-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
        networks:
            - book-network

volumes:
    dbdata:
    redisdata:

networks:
    book-network:
        driver: bridge
